services:
  - type: web
    name: vanet-sumo-backend
    runtime: docker
    repo: https://github.com/23ucs572-coder/VANET-based-Speed-Limit-Alert-System
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
